#!/bin/bash

set -e
set -x

if [ $# -ne 1 ]; then
	echo "USAGE: $0 VERSION" >&2
	exit 1
fi
grep -E '^[0-9]+[.][0-9]+([.][0-9]+)?$' <<<"$1"
V=$1

dir=$(mktemp -d) || exit 1
trap 'rm -rf "$dir"' EXIT QUIT TERM ABRT KILL INT

cd "$dir"
tar xf "/srv/www/download.geany.org/geany-$V.tar.gz"
S="$dir/geany-$V/"

cd /srv/www/www.geany.org/manual/
# new version is a symlink to the dev version
rm -f "$V"
mkdir "$V"
mv "$S/doc/geany.css" "$V/"
mv "$S/doc/geany.txt" "$V/"
mv "$S/doc/geany.html" "$V/index.html"
mv "$S/doc/images" "$V/"
mv "$S/HACKING" "$V/"
rst2html "$V/HACKING" > "$V/hacking.html"

# fix permissions, just in case
chgrp geany "$V/" -R
chmod a+rX "$V/" -R

# update the current version
ln -nsTf "$V" current

# list and check
ls -l
diff -u <(find 1.27 | cut -d/ -f2-) <(find "$V" | cut -d/ -f2-)
